### ISSUE TITLE
office365 giving error

### ISSUE THREAD

**Issue by devatsrs** [Webklex/laravel-imap#153]
[Webklex\IMAP\Exceptions\GetMessagesFailedException]      
  Object of class Closure could not be converted to string  

 

		$EmailClient = array (
			'host' => 'outlook.office365.com',
			'port' => 993,
			'encryption' => 'ssl',
			'validate_cert' => true,
			'username' => 'xxx',
			'password' => 'xxxxxxx',
			'protocol'      => 'imap'
		);

		 
		$oClient = new Client($EmailClient);
 		$oClient->connect();
 
 		/** @var \Webklex\IMAP\Folder $oFolder */
		if($oFolder = $oClient->getFolder("INBOX")){
 
 			$LastEmailReadDateTime = '2018-10-05 13:49:56';
 			$aMessage = $oFolder->messages(null)->since($LastEmailReadDateTime)->all()->get();
 

			echo "\n" . $oFolder->fullName;
			echo "\n aMessage " . count($aMessage);

		}

**Comment by Webklex** [comment]
Hi @devatsrs ,
please provide some additional information such as the used version and the complete error call stack.

Best reagrds

**Comment by devatsrs** [comment]
Hi @Webklex 

I have tried 2 versions and found fix in both versions.

**Version: "1.1.2"**

```

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: update `tblCronJob` set `updated_at` = 2018-10-05 23:33:29, `Active` = 0, `PID` =  where `CronJobID` = 76)' in /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Connection.php:624
Stack trace:
#0 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Connection.php(580): Illuminate\Database\Connection->runQueryCallback('update `tblCron...', Array, Object(Closure))
#1 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Connection.php(387): Illuminate\Database\Connection->run('update `tblCron...', Array, Object(Closure))
#2 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Connection.php(332): Illuminate\Database\Connection->affectingStatement('update `tblCron...', Array)
#3 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1740): Illuminate\Database\Connection->update('update `tblCron...', Array)
#4 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(288): Illuminate\Database\Query\Builder->update(Array)
#5 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1544): Illuminate\Database\Eloquent\Builder->update(Array)
#6 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1477): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#7 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1425): Illuminate\Database\Eloquent\Model->save()
#8 /var/www/html/service/app/lib/CronJob.php(0): Illuminate\Database\Eloquent\Model->update()
#9 /var/www/html/service/app/Console/Commands/ReadEmailsTickets.php(0): App\Lib\CronJob::deactivateCronJob()
#10 [internal function]: App\Console\Commands\ReadEmailsTickets->fire()
#11 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Container/Container.php(526): call_user_func_array(Array, Array)
#12 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Console/Command.php(115): Illuminate\Container\Container->call(Array)
#13 /var/www/html/service/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(257): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Console/Command.php(101): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/service/vendor/symfony/console/Symfony/Component/Console/Application.php(874): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/service/vendor/symfony/console/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ReadEmailsTickets), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/service/vendor/symfony/console/Symfony/Component/Console/Application.php(126): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/service/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(94): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/service/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 {main}  
```



On file 
webklex/laravel-imap/src/IMAP/Folder.php

issue at following line

`        $availableMessages = imap_search($this->getClient()->getConnection(), $query, SE_UID, $charset);
`
Fix 
```

//		"webklex/laravel-imap": "1.1.2" @version  1.1.2 fix
  	   if($this->getClient()->host == 'outlook.office365.com') {
                $availableMessages = imap_search($this->getClient()->getConnection(), $query, SE_UID);
            } else {
                $availableMessages = imap_search($this->getClient()->getConnection(), $query, SE_UID, $charset);
            }
```


**And Fix for version 1.2.9**

Replace following code on src/IMAP/Query/Query.php

      ```

      $available_messages->forPage($this->page, $this->limit)->each(function($msgno, $msglist) use(&$messages, $options) {
                    $oMessage = new Message($msgno, $msglist, $this->getClient(), $this->getFetchOptions(), $this->getFetchBody(), $this->getFetchAttachment(), $this->getFetchFlags());
                    switch ($options['message_key']){
                        case 'number':
                            $message_key = $oMessage->getMessageNo();
                            break;
                        case 'list':
                            $message_key = $msglist;
                            break;
                        default:
                            $message_key = $oMessage->getMessageId();
                            break;
                    }
                    $messages->put($message_key, $oMessage);
                });

```
 
With following code

```
                foreach($available_messages  as $msgno){

                    $oMessage = new Message($msgno, $msglist, $this->getClient(), $this->getFetchOptions(), $this->getFetchBody(), $this->getFetchAttachment(), $this->getFetchFlags());
                    switch ($options['message_key']){
                        case 'number':
                            $message_key = $oMessage->getMessageNo();
                            break;
                        case 'list':
                            $message_key = $msglist;
                            break;
                        default:
                            $message_key = $oMessage->getMessageId();
                            break;
                    }
                    $messages->put($message_key, $oMessage);
                }
```

**Comment by Webklex** [comment]
Hi @devatsrs,
please refer to #100 regarding your first problem.
```php
if($this->getCharset() === null){
    $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID);
}else{
    $available_messages = imap_search($this->getClient()->getConnection(), $this->getRawQuery(), SE_UID, $this->getCharset());
}
```

The second one is hard to tackle without any stack trace or a bit more information :)

Best regards

**Comment by devatsrs** [comment]
Thanks @Webklex    👍
