### ISSUE TITLE
Explode error

### ISSUE THREAD

**Issue by mennovanhout** [Webklex/laravel-imap#385]
**Describe the bug**
explode(): Argument #1 ($separator) cannot be empty.

Everything worked perfectly on the set-up it broke from one day to another with zero changes. It's probably caused by an email that came in.

**To Reproduce**
1. Freshly install laravel 8
2. install webklex/laravel-imap
3. get messages from a folder

```
$messages = $folder->messages()
            ->limit($limit, $page)
            ->setFetchBody(false)
            ->setFetchOrder("desc")
            ->all()
            ->get()
            ->reverse();
```

**Expected behavior**
It worked before i think a email came in that broke something in the code.

**Desktop / Server (please complete the following information):**
 - OS: Ubuntu local and same error on Forge production
- PHP: 8
 - Version 2.3.0

**Additional context**
Stack trace:

```
[2021-01-09 15:08:21] local.ERROR: explode(): Argument #1 ($separator) cannot be empty {"userId":1,"exception":"[object] (ValueError(code: 0): explode(): Argument #1 ($separator) cannot be empty at /var/www/html/vendor/webklex/php-imap/src/Structure.php:136)
[stacktrace]
#0 /var/www/html/vendor/webklex/php-imap/src/Structure.php(136): explode()
#1 /var/www/html/vendor/webklex/php-imap/src/Structure.php(82): Webklex\\PHPIMAP\\Structure->find_parts()
#2 /var/www/html/vendor/webklex/php-imap/src/Structure.php(71): Webklex\\PHPIMAP\\Structure->parse()
#3 /var/www/html/vendor/webklex/php-imap/src/Message.php(530): Webklex\\PHPIMAP\\Structure->__construct()
#4 /var/www/html/vendor/webklex/php-imap/src/Message.php(290): Webklex\\PHPIMAP\\Message->parseRawBody()
#5 /var/www/html/vendor/webklex/php-imap/src/Query/Query.php(242): Webklex\\PHPIMAP\\Message::make()
#6 /var/www/html/src/App/Web/Email/Controllers/EmailController.php(80): Webklex\\PHPIMAP\\Query\\Query->get()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): App\\Web\\Email\\Controllers\\EmailController->getMessages()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(692): Illuminate\\Routing\\Route->run()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(44): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(694): Illuminate\\Pipeline\\Pipeline->then()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(669): Illuminate\\Routing\\Router->runRouteWithinStack()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->dispatchToRoute()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#42 /var/www/html/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#44 /var/www/html/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#46 /var/www/html/vendor/tenancy/identification-driver-http/Middleware/EagerIdentification.php(40): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Tenancy\\Identification\\Drivers\\Http\\Middleware\\EagerIdentification->handle()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#51 /var/www/html/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#52 /var/www/html/server.php(21): require_once('...')
#53 {main}
"} 
```

**Comment by mennovanhout** [comment]
Seems that this if statement is failing in Structure.php line 116

```
if (($boundary = $this->getBoundary()) === null)  {
    throw new MessageContentFetchingException("no content found", 0);
}
```

($boundary = $this->getBoundary()) 

seems to return an empty string "" instead of null.

**Comment by mennovanhout** [comment]
The mail it fails at does have a boundry see:

Content-Type: multipart/related; boundary="00000000000028d20105b83a91d2"

however the find method fails to find it in Structure.php line 104

$this->header->find("/boundary=\"?([^\"]*)[\";\s]/")

**Comment by mennovanhout** [comment]
Mistake found first of all there is no null returned because in Structure.php: getBoundry()l
str_replace changes the null back in to a string (PHP 8).

Also the mail has a boundry:
Content-Type: MULTIPART/RELATED; BOUNDARY="1530194440-19055-1609978869=:57168"

But its failing thanks to capitals

$boundary = $this->header->find("/boundary=\"?([^\"]*)[\";\s]/");

returns null however

dd($boundary = $this->header->find("/BOUNDARY=\"?([^\"]*)[\";\s]/"));

returns "1530194440-19055-1609978869=:57168"

**Comment by mennovanhout** [comment]
This means that the getboundry function is failing :(.

**Comment by mennovanhout** [comment]
I made a solution for the failing getBoundry().

Please review:

https://github.com/Webklex/php-imap/pull/88
