### ISSUE TITLE
Call to a member function idle() on null

### ISSUE THREAD

**Issue by moshoodfakorede** [Webklex/laravel-imap#392]
**Describe the bug**
Call to a member function idle() on null while connecting to Outlook mail

**To Reproduce**
I am using the package to listen for new messages sent to an Outlook mail. Here's the code being run from a console command

```
public function handle()
    {
        /** @var Client $client */
        $client = \Client::account("default");
        try {
            $client->connect();
            Log::info('connected...');
        } catch (ConnectionFailedException $e) {
            Log::error('failed connecting...');
            Log::error($e->getMessage());
            return 1;
        }

        /** @var Folder $folder */
        try {
            $folder = $client->getFolder("INBOX");
        } catch (ConnectionFailedException $e) {
            Log::error($e->getMessage());
            return 1;
        } catch (FolderFetchingException $e) {
            Log::error($e->getMessage());
            return 1;
        }

        try {
            $folder->idle(function($message){
                NewMessageReceived::dispatch($message);
            });
        } catch (ConnectionFailedException $e) {
            Log::error($e->getMessage());
            return 1;
        }

        return 0;
    }
```

**Expected behavior**
After running the console command, i expect it to run normally and listen for new messages.

**Screenshots**

![error](https://user-images.githubusercontent.com/70203762/108711071-20346600-7515-11eb-8234-e25524cf7523.PNG)

Here's the error stack

```
[2021-02-22 13:43:14] local.INFO: connected...  
[2021-02-22 13:43:14] local.ERROR: Call to a member function idle() on null {"exception":"[object] (Error(code: 0): Call to a member function idle() on null at C:\\Users\\Moshood\\Code\\laravel_imap\\app\\Console\\Commands\\FetchMessagesCommand.php:91)
[stacktrace]
#0 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(36): App\\Console\\Commands\\FetchMessagesCommand->handle()
#1 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#2 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#3 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#4 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php(596): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#5 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(134): Illuminate\\Container\\Container->call(Array)
#6 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\symfony\\console\\Command\\Command.php(256): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#7 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Command.php(121): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#8 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\symfony\\console\\Application.php(971): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#9 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\symfony\\console\\Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\FetchMessagesCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#10 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\symfony\\console\\Application.php(166): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Console\\Application.php(93): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 C:\\Users\\Moshood\\Code\\laravel_imap\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Console\\Kernel.php(129): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 C:\\Users\\Moshood\\Code\\laravel_imap\\artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 {main}
"} 

```

**Desktop / Server (please complete the following information):**
 - OS: Windows
- PHP: 7.3.26
 - Version 2.4

**Comment by Webklex** [comment]
Hi @moshoodfakorede ,
thanks for your detailed report.

It seems like the folder "INBOX" can't be located?

Please go ahead and dump `$folder`.
```php
$folder = $client->getFolder("INBOX");
$folder1 = $client->getFolderByName("INBOX");
$folder2 = $client->getFolderByPath("INBOX");

dump([$folder, $folder1, $folder2]);
```

Please head over to the core repository https://github.com/Webklex/php-imap if it's still failing.

Best regards,

P.s.: take a look at this: https://www.php-imap.com/frameworks/laravel/commands
